In [1]:
import numpy as np

In [6]:
from torchvision import models
from torchvision.models import ResNet101_Weights
import torch

In [3]:
alexnet = models.AlexNet()
print(alexnet)

AlexNet(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(11, 11), stride=(4, 4), padding=(2, 2))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
    (3): Conv2d(64, 192, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
    (4): ReLU(inplace=True)
    (5): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
    (6): Conv2d(192, 384, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (7): ReLU(inplace=True)
    (8): Conv2d(384, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (9): ReLU(inplace=True)
    (10): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): ReLU(inplace=True)
    (12): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (avgpool): AdaptiveAvgPool2d(output_size=(6, 6))
  (classifier): Sequential(
    (0): Dropout(p=0.5, inplace=False)
    (1): Linear(in_features=9216, out_features=4096, bias=True)
 

In [5]:
resnet = models.resnet101(weights = ResNet101_Weights.IMAGENET1K_V1 )

Downloading: "https://download.pytorch.org/models/resnet101-63fe2227.pth" to C:\Users\Naman/.cache\torch\hub\checkpoints\resnet101-63fe2227.pth
100%|██████████| 171M/171M [00:26<00:00, 6.85MB/s] 


In [16]:
x = torch.tensor([1, 2, 3, 4])
x.shape

torch.Size([4])

In [15]:
x = torch.unsqueeze(x, 0)
x.shape

torch.Size([1, 4])

In [19]:
x = torch.unsqueeze(x, 1)
x.shape

torch.Size([4, 1])

In [39]:
a = torch.randn(2, 4)
a

tensor([[-0.3642, -0.8122,  1.7385,  0.3957],
        [-0.5702, -0.1112,  0.3370, -0.9829]])

In [35]:
a[0][1]

tensor(-0.8825)

In [40]:
torch.max(a, 1)

torch.return_types.max(
values=tensor([1.7385, 0.3370]),
indices=tensor([2, 2]))

In [26]:
torch.max(a)

tensor(1.9584)

In [42]:
torch.max(a, 0)

torch.return_types.max(
values=tensor([-0.3642, -0.1112,  1.7385,  0.3957]),
indices=tensor([0, 1, 0, 0]))

In [43]:
a

tensor([[-0.3642, -0.8122,  1.7385,  0.3957],
        [-0.5702, -0.1112,  0.3370, -0.9829]])

In [44]:
torch.sort(a, dim=0, descending=True)

torch.return_types.sort(
values=tensor([[-0.3642, -0.1112,  1.7385,  0.3957],
        [-0.5702, -0.8122,  0.3370, -0.9829]]),
indices=tensor([[0, 1, 0, 0],
        [1, 0, 1, 1]]))

In [45]:
torch.sort(a, dim=1, descending=True)

torch.return_types.sort(
values=tensor([[ 1.7385,  0.3957, -0.3642, -0.8122],
        [ 0.3370, -0.1112, -0.5702, -0.9829]]),
indices=tensor([[2, 3, 0, 1],
        [2, 1, 0, 3]]))

In [46]:
torch.cos(a)

tensor([[ 0.9344,  0.6879, -0.1669,  0.9227],
        [ 0.8418,  0.9938,  0.9437,  0.5546]])

In [47]:
import torch.nn as nn

In [48]:
# Example of target with class indices
loss = nn.CrossEntropyLoss()
input = torch.randn(3, 5, requires_grad=True)
target = torch.empty(3, dtype=torch.long).random_(5)
output = loss(input, target)
output.backward()


In [50]:
print("Input shape : ", input.shape)
print("Target shape : ", target.shape)
print("Output shape : ", output.shape)

Input shape :  torch.Size([3, 5])
Target shape :  torch.Size([3, 5])
Output shape :  torch.Size([])


In [51]:
print(input)

tensor([[-1.6604, -1.3080, -1.0912, -1.7825, -1.5898],
        [-1.1296,  1.7312, -1.4950,  1.2069, -0.9937],
        [-0.3546,  1.6221, -0.6936, -0.8118,  0.6960]], requires_grad=True)


In [53]:
print(target)


tensor([[0.1493, 0.3914, 0.2978, 0.0659, 0.0955],
        [0.2462, 0.0788, 0.1328, 0.2106, 0.3316],
        [0.0477, 0.0445, 0.0151, 0.8636, 0.0290]])


In [54]:
target.sum(dim=1)

tensor([1.0000, 1.0000, 1.0000])

In [55]:
input.sum(dim=1)

tensor([-7.4318, -0.6802,  0.4581], grad_fn=<SumBackward1>)

In [49]:
# Example of target with class probabilities
input = torch.randn(3, 5, requires_grad=True)
target = torch.randn(3, 5).softmax(dim=1)
output = loss(input, target)
output.backward()